{{- if .Values.deepwiki.storage.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.deepwiki.storage.name }}
  namespace: {{ .Values.deepwiki.namespace }}
  labels:
    app.kubernetes.io/name: deepwiki
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.deepwiki.storage.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.deepwiki.storage.accessModes }}
    - {{ . }}
    {{- end }}
  {{- if .Values.deepwiki.storage.storageClassName }}
  storageClassName: {{ .Values.deepwiki.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.deepwiki.storage.size }}
{{- end }}
